### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by fschutt** [d-dorazio/marching_squares#1]
Is this repo MIT-licensed? Just wanted to make sure I don't violate any copyright. Thanks.

**Comment by danieledapo** [comment]
Indeed, it is licensed under dual MIT/Apache-2.0. I've just added the license files to make it clear.

Thanks for pointing it out :+1:

**Comment by fschutt** [comment]
Ok, I adapted it slightly and also made it parallel: https://github.com/fschutt/marching-squares

I've published it on crates.io, so it's easily accessible for others: https://crates.io/crates/marching-squares

Thanks for your help!
